WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include
# ДЛя показа картинок в админке
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
]

WebBooks/catalog/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail')
]

WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField


# Жанр книги
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Введите жанр книги', verbose_name='Жанр книги')

    def __str__(self):
        return self.name


# Язык книги
class Language(models.Model):
    name = models.CharField(max_length=20, help_text='Введите язык книги', verbose_name='Язык книги')

    def __str__(self):
        return self.name


# Издательство
class Publisher(models.Model):
    name = models.CharField(max_length=20, help_text='Введите наименования издательство', verbose_name='Издательство')

    def __str__(self):
        return self.name


# Авторы
class Author(models.Model):
    first_name = models.CharField(max_length=100, help_text='Введите имя автора', verbose_name='Имя автора')
    last_name = models.CharField(max_length=100, help_text='Введите фамилию автора', verbose_name='Фамилия автора')
    data_of_birth = models.DateField(help_text='Введите дату рождения',
                                     verbose_name='Дата рождения', null=True, blank=True)
    about = HTMLField(help_text='Введите сведения об авторе', verbose_name='Сведения об авторе')
    photo = models.ImageField(upload_to='images', help_text='Загрузите фото автора', verbose_name='Фото автора',
                              null=True, blank=True)
    objects = models.Manager()

    def __str__(self):
        return self.last_name


# Книги
class Book(models.Model):
    title = models.CharField(max_length=200, help_text='Введите названия книги', verbose_name='Названия книги')
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE, help_text='Выберите жанр для книги',
                              verbose_name='Язык книги', null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE, help_text='Выберите язык книги',
                                 verbose_name='Язык книги', null=True)
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE, help_text='Выберите издательство',
                                  verbose_name='Издательство', null=True)
    year = models.CharField(max_length=4, help_text='Введите год издания', verbose_name='Год издания')
    author = models.ManyToManyField('Author', help_text='Выберите автора(ов) книги',
                                    verbose_name='Автор (Авторы) книги')
    summary = HTMLField(max_length=1000, help_text='Введите краткое описание книги',
                        verbose_name='Аннотация книги')
    isbn = models.CharField(max_length=13, help_text='Должно содержит 13 символов', verbose_name='ISBN книги')
    price = models.DecimalField(decimal_places=2, max_digits=7, help_text='Введите цену книги',
                                verbose_name='Цена (руб.)')
    photo = models.ImageField(upload_to='images', help_text='Загрузите изображение облика',
                              verbose_name='Изображение облика')
    objects = models.Manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Возвращает URL-адрес для доступа к
        # определенному экземпляру книги
        return reverse('book-detail', args=[str(self.pk)])

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])

    display_author.short_description = 'Авторы'


# состояние экземпляра книги
class Status(models.Model):
    name = models.CharField(max_length=20, help_text='Введите статус экземпляра книги',
                            verbose_name='Статус экземпляра книги')

    def __str__(self):
        return self.name


# экземпляр книги
class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20, null=True, help_text='Введите инвентарный номер экземпляра',
                               verbose_name='Инвентарный номер')
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True,
                               help_text='Изменить состояние экземпляра', verbose_name='Статус экземпляра книги')
    due_back = models.DateField(null=True, blank=True, help_text='Введите конец срока статуса',
                                verbose_name='Дата окончание статуса')
    objects = models.Manager()

    # Meta данные
    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

WebBooks/catalog/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import ListView, DetailView


def index(request):
    text_head = 'На нашем сайте вы можете получить книги в электронном виде'
    books = Book.objects.all()
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact=2).count()
    authors = Author.objects
    num_authors = Author.objects.count()
    # число посещений этого view, подсчитанное в переменной session
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'text_head': text_head,
        'books': books,
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'authors': authors,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }
    return render(request, 'catalog/index.html', context)


class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 3
    template_name = 'catalog/book_list.html'


class AuthorListView(ListView):
    model = Author
    context_object_name = 'authors'
    paginate_by = 4
    template_name = 'catalog/author_list.html'


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'catalog/book_detail.html'


class AuthorDetailView(DetailView):
    model = Author
    context_object_name = 'author'
    template_name = 'catalog/author_detail.html'

WebBooks/templates/catalog/author_detail.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="container text-start">
        <div class="row my-2">
            <h4>{{ author.first_name }} {{ author.last_name }}</h4>
            <p>Родился - {{ author.data_of_birth }}</p>
            <p>Фото (портрет)</p>
            <p><img src="{{ author.photo.url }}" alt="connect" style="max-height:200px"></p>
            <div class="row my-2">
                <div class="col-2 my-2">
                    <a href="{{ author.photo.url }}" class="btn btn-primary" target="_Ыank"> Показать</a>
                </div>
            </div>
            <div class="row my-2">
                {{ author.about }}
            </div>
        </div>
    </div>
{% endblock content %}

WebBooks/templates/catalog/author_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row text-center text-dark lh-2">
        <h4>Список авторов в базе данных!</h4>
    </div>
    {% if authors %}
        <table class="table table-striped table-bordered text-start">
            <thead>
            <tr>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Дата рождения</th>
                <th>Фото</th>
                <th>Показать фото</th>
            </tr>
            </thead>
            <tbody>
            {% for author in authors %}
                <tr>
                    <td><a href="{{ author.id }}">{{ author.last_name }}</a></td>
                    <td>{{ author.first_name }}</td>
                    <td>{{ author.data_of_birth }}</td>
                    <td><img src="{{ author.photo.url }}" alt="connect" style="height: 100px;"></td>
                    <td><a href="{{ author.photo.url }}" class="btn btn-primary" target="_blank">Показать</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    {% endif %}
{% endblock content %}

WebBooks/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script defer src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title></title>
</head>

<body>
<div class="container-fluid p-1 bg-primary text-white text-center">
    <div class="row">
        <div class="col-2 text-start">
            <img src="{% static 'images/logo.png' %}" width="70" height="70" alt="">
        </div>
        <div class="col-10 ">
            <h3>Мир книг - печатные и электронные интерактивные книги</h3>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row bg-warning text-center">
        <h6>
            <a href="{% url 'index' %}">Главная страница</a>
            <a href="{% url 'index' %}">О компании</a>
            <a href="{% url 'index' %}">Контакты</a>
            <a href="{% url 'login' %}">login</a>
        </h6>
    </div>
</div>

<div class="container-fluid">
    <div class="row text-center text-primary fs-1 fw-bold">
        <div>{% block header %}
        {% endblock header %}
        </div>
    </div>
    <div class="row text-start text-body">
        <div class="col-2 ">
            {% block sidebar %}
                <nav class="nav flex-column">
                    <a class="nav-link" href="{% url 'books' %}">Все книги</a>
                    <a class="nav-link" href="{% url 'authors' %}">Все авторы</a>
                </nav>
                {% if user.id_authenticated %}
                    <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Выход</a>
                    <div>Вошел{{ user.get_username }}</div>
                {% else %}
                    <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Выход</a>
                {% endif %}
            {% endblock sidebar %}
        </div>
        <div class="col-10">
            <div class="row text-center">
                {% block content %}
                {% endblock content %}

                <!-- пагинация -->
                <div class="pagination">
                    <span class="step-links">
                    {% if page_obj.paginator.num_pages > 1 %}
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; Первая</a>
                            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                        {% endif %}

                        <span class="current">
                            Стр. {{ page_obj.number }}
                                 из {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">Предыдущая &raquo;</a>
                        {% endif %}
                    {% endif %}
                    </span>
                </div>
                <!-- пагинация -->
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row bg-info text-center text-dark small lh-sm pt-2 my-2">
        {% block footer %}
            <p>Copyright ООО "Интеллектуальные информационные системы",
                2023. Все права защищены</p>
        {% endblock footer %}
    </div>
</div>
</body>
</html>

WebBooks/templates/catalog/book_detail.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="container text-start">
        <div class="row my-2">
            <h1>Название книги - "{{ book.title }}"</h1>
        </div>

        <div class="row my-2">
            <p><strong>Автор:</strong>
                {% for author in book.author.all %}
                    <a href="{% url 'authors' %}{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</a>
                {% endfor %}
        </div>

        <img src="{{ book.photo.url }}" alt="connect"
             style="max-height:200px">
        <a href="{{ book.photo.url }}"
           class="btn btn-primary"
           target="_blank"> Показать</a>
        <div class="row my-2">
            <div class="col">
                <p><strong>Цена:</strong> {{ book.price }} руб.</p>
            </div>
        </div>

        <div class="row my-2">
            <p><strong>Аннотация:</strong> {{ book.summary }}</p>
        </div>

        <div class="row my-2">
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Жанр:</strong> {{ book.genre }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>ISBN:</strong> {{ book.isbn }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Язык:</strong> {{ book.language }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Издательство:</strong> {{ book.publisher }}</p>
            </div>
        </div>

        <div style="margin-left:20px; margin-top:10px">
            <h4>Количество экземпляров книг в БД</h4>
            {% for copy in book.bookinstance_set.all %}
                <hr>
                <p class="text-muted">
                    <strong>Инвентарный номер:</strong> {{ copy.id }}</p>
                <p class="text-success">
                    <strong>Статус экземпляра книги:</strong> {{ copy.status }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

WebBooks/templates/catalog/book_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row text-center text-dark lh-2">
        <h4>Список книг в базе данных!</h4>
    </div>
    {% if books %}
        <table class="table table-striped table-bordered text-start">
            <thead>
            <tr>
                <th>Название</th>
                <th>Автор</th>
                <th>Жанр</th>
                <th>Обложка</th>
                <th>Показать обложку</th>
            </tr>
            </thead>
            <tbody>
            {% for book in books %}
                <tr>
                    <td><a href="{{ book.id }}">{{ book.title }}</a></td>
                    <td>{{ book.display_author }}</td>
                    <td>{{ book.genre }}</td>
                    <td><img src="{{ book.photo.url }}" alt="connect" style="height: 100px;"></td>
                    <td><a href="{{ book.photo.url }}" class="btn btn-primary" target="_blank">Показать</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    {% endif %}
{% endblock content %}

WebBooks/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% block title %}Мир книг{% endblock title %}
{% block header %}
    <h5>{{ text_head }}</h5>
{% endblock header %}
{% block content %}
    <div class="container-fluid my-2">
        <div class="row bg-success text-white mx-2">
            <div class="col text-center">
                <p>
                    Добро пожаловать на сайт<em>Мир книг</em>. Это очень
                    простой веб-сайт, написанный на Django и Bootstrap.
                    Разработан на Python в качестве учебного примера
                    с использованием PyCharm.
                </p>
            </div>
        </div>
        <div class="row text-center text-dark lh-2">
            <h4>Сведения из базы данных</h4>
        </div>
        <div class="row my-2 text-white">
            <div class="col mx-2 bg-primary">
                Количество книг - {{ num_books }}
            </div>
            <div class="col mx-2 bg-primary">
                Ha складе в наличии - {{ num_instances_available }}
            </div>
            <div class="col mx-2 bg-primary">
                Количество авторов - {{ num_authors }}
            </div>
            <div class="row text-center text-dark lh-2">
                <h3>Книги</h3>
            </div>
            {% if num_books > 0 %}
                <div class="row my-2">
                    {% for book in books %}
                        <div class="card" style="width: 9rem;">
                            <img src="{{ book.photo.url }}" class="card-img-top" alt="">
                            <div class="card-body">
                                <p class="card-text small text-dark">
                                    {{ book.title }},<br/> Цена: {{ book.price }} руб.
                                <hr/>
                                <button type="button" class="btn btn-info">
                                    <a href="{% url 'books' %}{{ book.id }}">Подробнее...</a>
                                </button>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="row text-center text-dark lh-2">
                <h6>Число посещений данной страницы - {{ num_visits }}</h6>
            </div>
        </div>
    </div>
{% endblock content %}